
services:
  # app:
  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #       container_name: springboot-app
  #       ports:
  #           - '8080:8080'
  #       depends_on:
  #           - mysql
  #           - redis
  #       environment:
  #           - DATABASE_HOST=mysql
  #           - DATABASE_PORT=3306
  #           # - DATABASE_USER=root
  #           # - DATABASE_PASSWORD=HoanHa
  #           - DATABASE_NAME=springmvctutorial
  #           - REDIS_HOST=redis
  #           - REDIS_PORT=6380

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  